name: Github Actions example

on: 
  push:
    branches:
      - development

jobs:
  test:
    name: Running units tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run : npm install

      
