name: Github Actions example 

on: 
  push:
    branches:
      - development

jobs:
  test:
    name: Running units tests 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install the dependances
        run : npm install
<<<<<<< HEAD
      - name: Run test
        run: npm run test

=======
      - name: build
        run: npm build
>>>>>>> 8fa0f17 (changed the branch in yml file)
      
